(function) @function
(name) @type
(number) @number
(string) @string
"." @keyword
"<-" @keyword
"@" @keyword
"\\" @keyword
"," @operator
";" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"(" @punctuation.bracket
")" @punctuation.bracket